name: Docker ECR Publish
description: Build, tag, and push Docker images to Amazon ECR
author: https://github.com/seek-oss
requirements:
  - docker
configuration:
  properties:
    build-context:
      type: string
    args:
      type: [array, string]
    additional-build-args:
      type: string
    branch-args:
      type: [array, string]
    branch-tags:
      type: [array, string]
    cache-from:
      type: [array, string]
    default-args:
      type: [array, string]
    default-tags:
      type: [array, string]
    dockerfile:
      type: string
    ecr-name:
      type: string
    tags:
      type: [array, string]
    target:
      type: string
  required: ['ecr-name']
