name: Docker ECR Publish
description: Build, tag, and push Docker images to Amazon ECR
author: https://github.com/raksha1
requirements:
  - docker
configuration:
  properties:
    build-context:
      type: string
    args:
      type: [array, string]
    additional-build-args:
      type: string
    branch-args:
      type: [array, string]
    branch-tags:
      type: [array, string]
    cache-from:
      type: [array, string]
    default-args:
      type: [array, string]
    default-tags:
      type: [array, string]
    dockerfile:
      type: string
    ecr-name:
      type: string
    account-id:
      type: string
    regions:
      type: [array, string]
    tags:
      type: [array, string]
    target:
      type: string
    add-latest-tag:
      type: boolean
  required: ['ecr-name']
