#!/usr/bin/env bash

set -euo pipefail

get_ecr_url() {
  local repository_name="$1"
  aws ecr describe-repositories \
    --repository-names "${repository_name}" \
    --output text \
    --query 'repositories[0].repositoryUri'
}

$(aws ecr get-login --no-include-email)
docker_file="${BUILDKITE_PLUGIN_DOCKER_ECR_PUBLISH_DOCKERFILE:-Dockerfile}"
image_name="$(get_ecr_url ${BUILDKITE_PLUGIN_DOCKER_ECR_PUBLISH_ECR_NAME})"

if ! docker pull "${image_name}:$BUILD_VERSION"; then
  echo "Image not cached, building"
  if [ "$BUILDKITE_BRANCH" == "$BUILDKITE_PIPELINE_DEFAULT_BRANCH" ]; then
    docker build . --file "${docker_file}" -t "${image_name}:$BUILD_VERSION" -t "${image_name}:latest" || exit 1
  else
    docker build . --file "${docker_file}" -t "${image_name}:branch-$BUILD_VERSION" || exit 1
  fi
  docker push "${image_name}"
fi || echo "Not found"

# Support using https://github.com/buildkite-plugins/docker-buildkite-plugin without an image
export BUILDKITE_PLUGIN_DOCKER_IMAGE="${image_name}"
