#!/usr/bin/env bash

set -euo pipefail

get_ecr_url() {
  local repository_name="$1"
  aws ecr describe-repositories \
    --repository-names "${repository_name}" \
    --output text \
    --query 'repositories[0].repositoryUri'
}

compute_tag() {
  local docker_file="$1"
  local sums=($(sha1sum "${docker_file}"))
  while IFS='=' read -r name _ ; do
    if [[ $name =~ ^(BUILDKITE_PLUGIN_DOCKER_ECR_PUBLISH_CACHE_ON_[0-9]+) ]] ; then
      local sha=($(sha1sum "${!name}"))
      sums="${sums}${sha:-''}"
    fi
  done < <(env | sort)
  echo "${sums}" | sha1sum | cut -c-7
}

$(aws ecr get-login --no-include-email)
docker_file="${BUILDKITE_PLUGIN_DOCKER_ECR_PUBLISH_DOCKERFILE:-Dockerfile}"
image_name="$(get_ecr_url ${BUILDKITE_PLUGIN_DOCKER_ECR_PUBLISH_ECR_NAME})"
image_tag="$(compute_tag ${docker_file})"

if ! docker pull "${image_name}:${image_tag}"; then
  echo "Image not cached, building"
  if [ "$BUILDKITE_BRANCH" == "$BUILDKITE_PIPELINE_DEFAULT_BRANCH" ]; then
    docker build . --file "${docker_file}" -t "${image_name}:${image_tag}" -t "${image_name}:latest" || exit 1
  else
    docker build . --file "${docker_file}" -t "${image_name}" -t "$BUILDKITE_BUILD_NUMBER" || exit 1
  fi
  docker push "${image_name}"
fi || echo "Not found"

# Support using https://github.com/buildkite-plugins/docker-buildkite-plugin without an image
export BUILDKITE_PLUGIN_DOCKER_IMAGE="${image_name}"