#!/usr/bin/env bash

set -euo pipefail

get_ecr_url() {
  local repository_name="$1"
  aws ecr describe-repositories \
    --repository-names "${repository_name}" \
    --output text \
    --query 'repositories[0].repositoryUri'
}

plugin_read_list_into_result() {
  local prefix="$1"
  local parameter="${prefix}_0"
  result=()

  if [[ -n "${!parameter:-}" ]]; then
    local i=0
    local parameter="${prefix}_${i}"
    while [[ -n "${!parameter:-}" ]]; do
      result+=("${!parameter}")
      i=$((i+1))
      parameter="${prefix}_${i}"
    done
  elif [[ -n "${!prefix:-}" ]]; then
    result+=("${!prefix}")
  fi

  [[ ${#result[@]} -gt 0 ]] || return 1
}

push_additional_tags() {
  local tags_parameter="$1"
  local branch_type="$2"
  
  if plugin_read_list_into_result ${tags_parameter} ; then
    for tag in "${result[@]}" ; do
      docker tag "${branch_type}" "${image_name}:$tag"
      docker push "${image_name}:$tag"
    done
  fi
}

$(aws ecr get-login --no-include-email)
docker_file="${BUILDKITE_PLUGIN_DOCKER_ECR_PUBLISH_DOCKERFILE:-Dockerfile}"
image_name="$(get_ecr_url ${BUILDKITE_PLUGIN_DOCKER_ECR_PUBLISH_ECR_NAME})"

if [ "$BUILDKITE_BRANCH" == "$BUILDKITE_PIPELINE_DEFAULT_BRANCH" ]; then
  docker build . --file "${docker_file}" --build-arg "BRANCH_TYPE=master" -t "master" || exit 1
  docker tag "master" "${image_name}:latest"
  push_additional_tags BUILDKITE_PLUGIN_DOCKER_ECR_PUBLISH_DEFAULT_TAGS "master"
  docker push "${image_name}:latest"
else
  docker build . --file "${docker_file}" -t "branch" || exit 1
  push_additional_tags BUILDKITE_PLUGIN_DOCKER_ECR_PUBLISH_BRANCH_TAGS "branch"
fi